name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "strapiherokuapp" #Must be unique in Heroku
          heroku_email: "lexferramirez@gmail.com"
          usedocker: true
          docker_build_args: |
            ${{secrets.DATABASE_HOST}}
            ${{secrets.DATABASE_PORT}}
            ${{secrets.DATABASE_NAME}}
            ${{secrets.DATABASE_USERNAME}}
            ${{secrets.DATABASE_PASSWORD}}
            ${{secrets.DATABASE_SCHEMA}}
        env:
          DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          DATABASE_SCHEMA: ${{secrets.DATABASE_SCHEMA}}
          

